name: deploy_train_to_azure_cloud_ml

on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' # install the python version needed
          script: |
            add_path("")
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r req_to_push_azure.txt

      - name: create json config for azure ML
        id: json_1
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.secret_json }}

      - name: create json config for azure Blob
        id: json_2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config_blob.json"
          json: ${{ secrets.secret_json_blob }}

      - name: execute training deployment
        working-directory: ./Azure_scripts
        run: 
          python3 4_deploy_train.py