name: deploy_train_to_azure_cloud_ml

on:
  push:
    branches:
      - 'release'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' # install the python version needed
          script: |
            add_path("")
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r req_to_push_azure.txt

      - name: create json config for azure ML
        id: json_1
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.secret_json }}
          dir: 'Azure_scripts/'
      - name: create json config for azure Blob
        id: json_2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config_blob.json"
          json: ${{ secrets.secret_json_blob }}
          dir: 'Azure_scripts/'
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
      - name: Login via Az cli
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: execute training deployment
        working-directory: ./Azure_scripts
        run: 
          python3 4_deploy_train.py
      
